build:
	gcc main.c includes/matrix_multiplication.c includes/rotation_matrix.c -lm -o output

run: 
	./output

testbuild:
	gcc test_matrix_main.c test_matrix_functions.c unity_test/unity.c -Iunity_test -lm -o output
